- name: "{{ cluster_name }}: Get enabled auth methods"
  tags: [vault-kubernetes-auth, auth]
  command: >-
    vault auth list -format json
  changed_when: false
  register: auths_enabled

- name: "{{ cluster_name }}: Enable kubernetes auth"
  tags: [vault-kubernetes-auth, auth]
  command: >-
    vault auth enable -path kubernetes/{{ cluster_name }} kubernetes
  when: >-
    "kubernetes/{}/".format(cluster_name) not in (auths_enabled.stdout|from_json)

- name: "{{ cluster_name }}: Configure kubernetes auth"
  tags: [vault-kubernetes-auth, auth]
  command: >-
    vault write auth/kubernetes/{{ cluster_name }}/config
    kubernetes_host=https://kubernetes.default.svc

- name: "{{ cluster_name }}: Get roles"
  tags: [vault-kubernetes-auth, role]
  command: >-
    vault list -format json auth/kubernetes/{{ cluster_name }}/role
  changed_when: false
  failed_when: roles.rc not in [0, 2]
  register: roles

- name: "{{ cluster_name }}: Create role for clustersecretstore"
  tags: [vault-kubernetes-auth, role]
  command: >-
    vault write auth/kubernetes/{{ cluster_name }}/role/nerc-secret-reader
        bound_service_account_names=vault-nerc-secret-reader
        bound_service_account_namespaces=external-secrets-config
        policies={{ cluster_name }}-reader
  when: >-
    "{}-reader".format(cluster_name) not in (roles.stdout|from_json)
